# Example rfetch config file
# Place this in ~/.config/rfetch/

# modules = ["user_host", "shell", "distro", "packages", "uptime", "memory", "kernel", "ip", "cpu", "disk_usage", "process_num", "arch", "temp", "locale", "device_name", "time", "date", 
# "battery" # This module only works if rfetch has been compiled with the 'battery' feature, see README.md
#]
modules = ["user_host", "shell", "distro", "packages", "uptime", "memory", "kernel"]
delimiter = "~>"
title_color = "blue"

[user_host]
line = true
line_symbol = "â”"
line_color = "magenta"

[colors]
enabled = true
show_bg_colors = false

[ip]
public = false
